AllCops:
  TargetRubyVersion: 2.5

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/DateTime:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/AlignParameters:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15
